db:
  image: mariadb:latest
  environment:
    MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    MYSQL_DATABASE: ${DB_NAME}
    MYSQL_USER: ${DB_USER} 
    MYSQL_PASSWORD: ${DB_PASS}
  volumes:
   - ./dockerconfs/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
   - ../docker-volumes/db-1:/var/lib/mysql
  ports:
    - "127.0.0.1:3306:3306"
  command: --default-authentication-plugin=mysql_native_password

web:
  image: quay.io/sartography/mt-dev:r01
  environment:
    JDBC_URL: jdbc:mysql://db:3306/r0?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
    import.mode: export
    import.user name: daniel.h.funk@gmail.com
    import.password: 1234!@#$Abc
    import.url: http://localhost:8080
    import.path: /tmp
    import.delete: "true"
    import.rate.in.milliseconds: 60000
  volumes:
   - ./dockerconfs/context.xml:/usr/local/tomcat/conf/context.xml
  ports:
   - "127.0.0.1:80:8080"
   - "127.0.0.1:8001:8000"
  links:
    - db
